Repository teamcubation/byma-front, pull requests merged in 2024-12, with the labels that each got.

#5 Feature/login
  heber-especies-front/README.md
  heber-especies-front/index.html
  heber-especies-front/package-lock.json
  heber-especies-front/package.json
  heber-especies-front/src/App.tsx
  heber-especies-front/src/assets/img/BYMA-Logo-Login-2.svg
  heber-especies-front/src/assets/img/BYMA-Logo-Login.svg
  heber-especies-front/src/assets/img/banner-login.png
  heber-especies-front/src/assets/img/bg-light-404.svg
  heber-especies-front/src/assets/img/bg-login.svg
  heber-especies-front/src/components/Navbar.tsx
  heber-especies-front/src/components/PrivateRoute.tsx
  heber-especies-front/src/components/features/Pagina404/Pagina404.tsx
  heber-especies-front/src/components/features/gerente/AbmGerentes.tsx
  heber-especies-front/src/components/features/login/AlertByma.tsx
  heber-especies-front/src/components/features/login/LogInForm.tsx
  heber-especies-front/src/components/features/login/LogInFormItem.tsx
  heber-especies-front/src/components/features/login/LoginPage.tsx
  heber-especies-front/src/components/features/login/login.scss
  heber-especies-front/src/components/ui/button.tsx
  heber-especies-front/src/components/ui/card.tsx
  heber-especies-front/src/components/ui/form.tsx
  heber-especies-front/src/components/ui/input.tsx
  heber-especies-front/src/components/ui/label.tsx
  heber-especies-front/src/index.scss
  heber-especies-front/src/main.tsx
  heber-especies-front/src/utils/hooks/useAuth.ts
  heber-especies-front/tailwind.config.js
Labels: Review effort [1-5]: 4

#4 Feature/botones
  heber-especies-front/src/components/button/ButtonIcon.scss
  heber-especies-front/src/components/button/ButtonIcon.tsx
  heber-especies-front/src/components/button/ButtonText.scss
  heber-especies-front/src/components/button/ButtonText.tsx
  heber-especies-front/src/components/button/ButtonWithIcon.scss
  heber-especies-front/src/components/button/ButtonWithIcon.tsx
  heber-especies-front/src/components/button/icon-button/add-azul.svg
  heber-especies-front/src/components/button/icon-button/add-disable.svg
  heber-especies-front/src/components/button/icon-button/add-gris-hover.svg
  heber-especies-front/src/components/button/icon-buttonIcon/bell-black.svg
  heber-especies-front/src/components/button/icon-buttonIcon/bell-white.svg
  heber-especies-front/src/components/button/icon-buttonIcon/interrogative-black.svg
  heber-especies-front/src/components/button/icon-buttonIcon/interrogative-white.svg
  heber-especies-front/src/components/button/icon-buttonIcon/major-black.svg
  heber-especies-front/src/components/button/icon-buttonIcon/major-white.svg
  heber-especies-front/src/components/button/icon-buttonIcon/minor-black.svg
  heber-especies-front/src/components/button/icon-buttonIcon/minor-white.svg
Labels: Review effort [1-5]: 3

#8 Update Develop
  heber-especies-front/package-lock.json
  heber-especies-front/src/MainLayout.tsx
  heber-especies-front/src/components/checkbox/Checkbox.scss
  heber-especies-front/src/components/checkbox/checkbox.tsx
  heber-especies-front/src/components/checkbox/form.tsx
  heber-especies-front/src/components/input/icons/error.svg
  heber-especies-front/src/components/input/icons/eye.svg
  heber-especies-front/src/components/input/icons/eyeClose.svg
  heber-especies-front/src/components/input/icons/lock.svg
  heber-especies-front/src/components/input/icons/notice.svg
  heber-especies-front/src/components/input/icons/success.svg
  heber-especies-front/src/components/input/icons/user.svg
  heber-especies-front/src/components/input/icons/warning.svg
  heber-especies-front/src/components/input/input.scss
  heber-especies-front/src/components/input/input.tsx
  heber-especies-front/src/components/input/myForm.tsx
  heber-especies-front/src/components/radio-button/App.tsx
  heber-especies-front/src/components/radio-button/RadioButton.scss
  heber-especies-front/src/components/radio-button/RadioButton.tsx
  heber-especies-front/src/components/switch/App.tsx
  heber-especies-front/src/components/switch/Switch.scss
  heber-especies-front/src/components/switch/Switch.tsx
  heber-especies-front/src/components/textarea/form.tsx
  heber-especies-front/src/components/textarea/textarea.scss
  heber-especies-front/src/components/textarea/textarea.tsx
Labels: Review effort [1-5]: 4

#10 Fix Develop MainLayout.tsx
  heber-especies-front/src/MainLayout.tsx
Labels: Review effort [1-5]: 2

#11 Feature/abm billetera
  heber-especies-front/src/App.tsx
  heber-especies-front/src/MainLayout.tsx
  heber-especies-front/src/components/Navbar.tsx
  heber-especies-front/src/components/billetera/CardBilletera.tsx
  heber-especies-front/src/components/billetera/FormBilletera.tsx
  heber-especies-front/src/components/billetera/MisBilleteras.tsx
  heber-especies-front/src/components/billetera/types/typeBilletera.ts
  heber-especies-front/src/components/billetera/types/typeInputFieldProps.ts
  heber-especies-front/src/components/billetera/utils/FormInputField.tsx
  heber-especies-front/src/components/billetera/utils/validationSchema.ts
  heber-especies-front/src/components/button/ButtonText.scss
  heber-especies-front/src/components/button/ButtonText.tsx
  heber-especies-front/src/services/BilleteraService.ts
Labels: Review effort [1-5]: 4

#12 puertos front finalizado, falta billeteras
  heber-especies-front/package-lock.json
  heber-especies-front/src/MainLayout.tsx
  heber-especies-front/src/components/EditarEmisor.tsx
  heber-especies-front/src/components/MisEmisores.tsx
  heber-especies-front/src/components/NuevoEmisor.tsx
  heber-especies-front/src/components/acdis/MisAcdis.tsx
  heber-especies-front/src/components/especie/FormEspecie.tsx
  heber-especies-front/src/components/especie/MisEspecies.tsx
  heber-especies-front/src/components/suscripcion/suscripciones.json
  heber-especies-front/src/services/AcdiService.ts
  src/api.js
Labels: Review effort [1-5]: 4

#13 fixes en front finalizado
  heber-especies-front/src/components/EditarEmisor.tsx
  heber-especies-front/src/components/MisEmisores.tsx
  heber-especies-front/src/components/NuevoEmisor.tsx
  heber-especies-front/src/components/PrivateRoute.tsx
  heber-especies-front/src/components/acdis/MisAcdis.tsx
  heber-especies-front/src/components/billetera/FormBilletera.tsx
  heber-especies-front/src/components/especie/FormEspecie.tsx
  heber-especies-front/src/components/features/gerente/AbmGerentes.tsx
  heber-especies-front/src/components/features/gerente/FormGerente.tsx
  heber-especies-front/src/components/ui/checkbox.tsx
Labels: Review effort [1-5]: 3
